title: Ralph Hightower @ github.io [Gateway — Website]

author:
  name: Ralph Hightower 
  #email: ralph.hightower@gmail.com
  #street_address:
  city: Chapin
  state: South Carolina
  zip_code: 29036
  country: United States of America
  #phone:
  email_marketing: There are two types of marketing by emails <br />1) Permission based marketing: Send an introductory email asking for permission to send email marketing. If I respond "Okay", then you may proceed.<br />2) Forgiveness based marketing: Spammer  just goes ahead and blasts me with spam, offering a link to unsubscribe. Why is it my responsibility to unsubscribed from emails that I never subscribed to?<br />Don't assume that your email *"got lost"*. I received it. It's just a waste of my time to respond. 
description: > # this means to ignore newlines until "show_excerpts:"
  Ralph Hightower GitHub Top Level — Links to Primary Repositories

show_excerpts: true # set to true to show excerpts on the homepage

timezone: America/New_York
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d %I:%M:%S.%L %p %Z" # "%b %-d, %Y"

  # generate social links in footer
social_links:
     - { platform: devto,          user_url: "https://dev.to/RalphHightower"}
  #   - { platform: dribbble,       user_url: "https://dribbble.com/RalphHightower" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/ralph.hightower" }
     - { platform: flickr,         user_url: "https://www.flickr.com/photos/RalphHightower" }
     - { platform: github,         user_url: "https://github.com/RalphHightower" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/RalphHightower" }
  #   - { platform: keybase,        user_url: "https://keybase.io/RalphHightower" }
     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/RalphHightower" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/RalphHightower" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/RalphHightower" }
     - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/19978043/ralph-hightower" }
  #   - { platform: telegram,       user_url: "https://t.me/RalphHightower" }
  #   - { platform: twitter,        user_url: "https://twitter.com/RalphHightower" }
     - { platform: youtube,        user_url: "https://www.youtube.com/@RalphHightower" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
# Build settings
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag# generate social links in footer
