# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: metrics:
  permissions:
    contents: write
    pull-requests: write
  steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: RalphHightowerMetrics.svg
        output_action: pull-request

    - uses: lowlighter/metrics@latest
      with:
        filename: my-metrics-1.svg
        output_action: pull-request-merge
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main", "_staging", "master"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - repo
          #  - public_repo
          #  - read:project
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)

          # Options
          user: RalphHightower
          template: markdown
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York 
          plugin_16personalities: yes
          plugin_16personalities_scores: yes
          plugin_16personalities_sections: personality
          plugin_16personalities_url: ${{secrets.SIXTEEN_PERSONALITIES_URL}}
          plugin_discussions: yes
          plugin_discussions_categories: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 19978043
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 4
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-top, questions-recent
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 14
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{secrets.GOOGLE_MAPS_TOKEN}}
          plugin_traffic: yes
          repositories_forks: yes
